#### 1. 异常或错误的情形

> 1. 语法错误：可能格式错误
> 2. 运行时错误：空指针异常，数组越界，除数为0
> 3. 逻辑错误：运行结果与预想结果不一样

#### 2. 异常结构

> - 从分类角度
>
> 1. Error：程序运行中，程序无法处理的问题
>    1. VirtulMachineError：虚拟机错误
>       1. StackOverFlowError：栈溢出
>       2. OutOfMemoryError：内存不够
>    2. AWTError
> 2. Exception：程序本身可以处理的异常
>    1. IOException：IO流异常
>       1. EOFException
>       2. FileNotFoundException
>    2. SQLException：数据库异常
>    3. RuntimeException：**运行时异常，Java编译器不会检查它**：**当程序中可能出现这类异常，即使没有用try-catch语句捕获它，也没有用throws子句声明抛出它，也会编译通过**
>       1. ArrithmeticException
>       2. MissingResourceException
>       3. ClassNotFoundException
>       4. NullPointerExpection：空指针
>       5. IllegalArgumentException
>       6. ArrayIndexOutOfBoundException：下标越界
>       7. UnkownTypeException
>
> - 从编译器是否要强制处理
>   1. 可查异常：除开RuntimeException及其子类以外，其他Exception类及其子类：**编译器会检查它：当程序中可能出现这类异常，要么用try-catch语句捕获它，要么用throws子句声明抛出它，否则编译不会通过。**
>   2. 不可查异常：**运行时异常和错误**

#### 3. 异常处理机制

> 1. 抛出异常：
>    - 运行时异常：将由Java运行时系统自动抛出
>    - Error：不做任何抛出声明，永远不允许发生的
>    - 可查异常：必须声明将抛出的异常
> 2. 捕捉异常：
>    - 潜在的异常处理器是异常发生时依次存留在调用栈中的方法的集合
>    - 运行时系统从发生异常的方法开始，依次回查调用栈中的方法，直至找到含有合适异常处理器的方法并执行。当运行时系统遍历调用栈而未找到合适 的异常处理器，则运行时系统终止
> 3. try\catch\finally的执行顺序
>    - try没有捕获到异常：跳过catch，执行finally语句块及其后的语句
>    - try捕获异常，但是catch没有处理：将异常抛给JVM处理，finally语句块会被执行，但是之后的语句不会执行
>    - try捕获异常，catch进行匹配异常，匹配成功，执行该语句块，执行finally块，执行之后的语句；

#### 4.断言

> 定义：一种调试程序的方式：assert
>
> 断言结果如果为true，继续执行，如果失败，就抛出AssertionError，程序结束退出

#### 5. 面试常见

> 1. Java中final，finally，finalize的区别？
>
>    > - final：关键字，用来定义常量，让类不能被继承，让方法不能被重写
>    > - finally：关键字，和try/try...catch连用：无论又没异常，异常又没被处理，都会被执行：一般用来关闭资源
>    > - finalize：方法，其中的对象被销毁之前会被垃圾回收
>
> 2. Java中throw和throws的区别？
>
>    > - throw：抛出一个异常对象到运行时进行处理
>    > - throws：声明可能抛出的异常
>
> 3. 检查异常和不检查异常的区别？
>
>    > - 检查异常：不进行try...catch捕获，或throws声明，编译都不会通过；而非检查异常：不要求
>    > - 检查异常：除开RunntimeException及其子类外的所有异常，非检查异常为运行时异常和错误
>
> 4. try-with-resource：Java7升级的特性：当程序运行完try..catch，运行环境自动关闭资源
>
>    ```java
>    try(MyResource mr = new MyResource()){
>        
>    }catch(Exception e){
>        
>    }
>    ```
>
> 5. 在多个catch子句中的异常对象是不可变的
>
>    ```java
>    try{
>        
>    }catch(IOException e){
>        e = new Exception();// 错误
>    }
>    catch(Exception e){
>        e.printStackTrace();
>    }
>    ```

